main: me.prisonranksx.PrisonRanksX
version: "2.8.7"
name: PrisonRanksX
author: "TheGaming999"
depend: [Vault]
softdepend: [PlaceholderAPI,MVdWPlaceholderAPI,HolographicDisplays,ActionUtil,PermissionsEX,GroupManager,LuckPerms,DecentHolograms]
api-version: 1.13